### ISSUE TITLE
Get error on Composer install

### ISSUE THREAD

**Issue by big-inc** [ilirhushi/laravel5.5-angular4#11]
Hi, 

I am getting error on composer install step, can you guide me on it, 
here is the screenshot of error 
[https://i.imgur.com/6q8a3GZ.png](https://i.imgur.com/6q8a3GZ.png)

Please advise, 

Thanks
Imran

**Comment by sheensol** [comment]
Hi,

I am getting error on composer install step, can you guide me on it,
here is the screenshot of error
https://i.imgur.com/6q8a3GZ.png

Please advise,

Thanks
Imran

**Comment by ilirhushi** [comment]
Hi @sheensol @big-inc ,

you might have problem with your php version or the .pem file of the SSL, anyway check this link https://gyazo.com/ef952a13bbf04703033b70e66e60047a might help you

**Comment by ilirhushi** [comment]
Closing this because I managed to install the project.
