### ISSUE TITLE
Mixing of Laravel and angular 

### ISSUE THREAD

**Issue by jazzuv** [ilirhushi/laravel5.5-angular4#13]
Hello 

Can you elaborate how you mixed laravel and angular  with simple way.

**Comment by ilirhushi** [comment]
@jazzuv what I have done is as follows:

1. if you got **web.php** you have "/" route that return the index.blade.php view
2. from there it is bootstrapped the Angular with the following tag:  <app-root></app-root> 
3. and everything else then in frontend is handled by the Angular and Laravel handling the backend part

And if you go to this repository you will see a different approach: https://github.com/ilirhushi/laravel-angular6-material

In here Laravel and Angular are separated and I like more this approach having them totally separated
