### ISSUE TITLE
Can you please show us how its gonna communicate with laravel api with one example please and also there is no support for AdminLte as i used some classes in template but didn't work

### ISSUE THREAD

**Issue by Afarooq143** [ilirhushi/laravel5.5-angular4#5]

**Comment by ilirhushi** [comment]
I created a Service for the Angular side in how to make calls from the Angular to the Backend, also at the home component you have a demo request how to do the request to the backend.
About the AdminLTE, it is available for the moment only for the Laravel side, I am working on it to make it available even for the Angular side.
Thank you for the issue @Afarooq143 

**PS.> Below is the response of the demo request:**
<img width="1273" alt="screenshot at jan 31 00-13-46" src="https://user-images.githubusercontent.com/10850562/35597145-513cda76-061d-11e8-9652-642e843872fb.png">

**Comment by ilirhushi** [comment]
I am closing this one.
