### ISSUE TITLE
Laravel routes VS  angular  routes : the communicate between laravel and angular dosn't work 

### ISSUE THREAD

**Issue by aminodrago** [ilirhushi/laravel5.5-angular4#6]
when i click on Admin Template link
``` js
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'admin-template'
Error: Cannot match any routes. URL Segment: 'admin-template'
```

**Comment by ilirhushi** [comment]
For the moment AdminLTE you can use it only from Laravel. I am working to use it even from the Angular side.
Thank you for reporting it @aminodrago .

**Comment by ilirhushi** [comment]
Hey @aminodrago ,
I upgraded to Angular 5 and added the AdminLTE to Angular so you can checkout the new version.
Thank you.

**Comment by ilirhushi** [comment]
I am closing this one.
